//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnnualReview
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerPerformanceReview
    {
        public int ID { get; set; }
        public string ManagerEID { get; set; }
        public string StaffEID { get; set; }
        public Nullable<bool> isSubmited { get; set; }
        public Nullable<bool> isReviewed { get; set; }
        public Nullable<bool> isShown { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public Nullable<bool> isSaved { get; set; }
    }
}
