//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnnualReview
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MasterContactListEntities : DbContext
    {
        public MasterContactListEntities()
            : base("name=MasterContactListEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<EmployeePerformanceReview> EmployeePerformanceReviews { get; set; }
        public virtual DbSet<ManagerPerformanceReview> ManagerPerformanceReviews { get; set; }
        public virtual DbSet<PerformanceReviewDetail> PerformanceReviewDetails { get; set; }
        public virtual DbSet<PerformanceReviewEditLog> PerformanceReviewEditLogs { get; set; }
    
        public virtual ObjectResult<spAnnualPR_GetImageByEID_Result> spAnnualPR_GetImageByEID(string employeeID)
        {
            var employeeIDParameter = employeeID != null ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAnnualPR_GetImageByEID_Result>("spAnnualPR_GetImageByEID", employeeIDParameter);
        }
    
        public virtual ObjectResult<spAnnualPR_GetImageByEID_Test_Result> spAnnualPR_GetImageByEID_Test(string employeeID)
        {
            var employeeIDParameter = employeeID != null ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAnnualPR_GetImageByEID_Test_Result>("spAnnualPR_GetImageByEID_Test", employeeIDParameter);
        }
    
        public virtual ObjectResult<spAnnualPR_getInfoLogByEID_Result> spAnnualPR_getInfoLogByEID(string employeeID)
        {
            var employeeIDParameter = employeeID != null ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAnnualPR_getInfoLogByEID_Result>("spAnnualPR_getInfoLogByEID", employeeIDParameter);
        }
    
        public virtual ObjectResult<spAnnualPR_ListManagers_Test_Result> spAnnualPR_ListManagers_Test(string employeeID)
        {
            var employeeIDParameter = employeeID != null ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAnnualPR_ListManagers_Test_Result>("spAnnualPR_ListManagers_Test", employeeIDParameter);
        }
    
        public virtual ObjectResult<spAnnualPR_SearchImageByEID_Test_Result> spAnnualPR_SearchImageByEID_Test(string employeeID)
        {
            var employeeIDParameter = employeeID != null ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spAnnualPR_SearchImageByEID_Test_Result>("spAnnualPR_SearchImageByEID_Test", employeeIDParameter);
        }
    }
}
