//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnnualReview
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceReviewDetail
    {
        public int ID { get; set; }
        public string EmployeeID { get; set; }
        public string SelfEvaluation { get; set; }
        public string StaffPerformanceSummary { get; set; }
        public string ManagerAssessment { get; set; }
        public string ManagerPerformanceSummary { get; set; }
        public Nullable<int> Criteria1 { get; set; }
        public Nullable<int> Criteria2 { get; set; }
        public Nullable<int> Criteria3 { get; set; }
        public Nullable<int> Criteria4 { get; set; }
        public Nullable<int> Criteria5 { get; set; }
        public Nullable<int> Criteria6 { get; set; }
        public Nullable<int> Criteria7 { get; set; }
        public Nullable<int> Criteria8 { get; set; }
        public Nullable<int> Criteria9 { get; set; }
        public Nullable<int> Criteria10 { get; set; }
        public Nullable<int> Criteria11 { get; set; }
        public Nullable<int> Criteria12 { get; set; }
        public Nullable<int> Criteria13 { get; set; }
        public Nullable<int> Criteria14 { get; set; }
        public Nullable<int> Criteria15 { get; set; }
        public string StaffGoals { get; set; }
        public string StaffComments { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public string Signature { get; set; }
        public string ManagerSignature { get; set; }
    }
}
